name: Generate vsix

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.0
        cache: 'npm'
    - run: npm ci
    - name: install vsce
      run: npm install -g @vscode/vsce
    - name: build
      run: npm vsce package
    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: gearbar vsix
        path: gearbar*.vsix
